### ISSUE TITLE
Problem with docs

### ISSUE THREAD

**Issue by jeroen** [ropensci/restez#16]
See the build log: https://dev.ropensci.org/job/restez/lastBuild/console

Generating the documentation fails with this error:

```
── Building articles ───────────────────────────────────────────────────────────
Warning: Vignettes missing from index: restez
Writing 'articles/index.html'
Reading 'vignettes/1_rodents.Rmd'
Error : callr subprocess failed: other/rodent_db.R must be run first!
Error: callr subprocess failed: callr subprocess failed: other/rodent_db.R must be run first!
```

Any guess what could cause this?

**Comment by DomBennett** [comment]
Ah...

`restez` downloads whole chunks of online biological sequence data.

Initially, I built the doc examples around simple downloaded examples. But to make the examples more realistic, I downloaded all rodent sequence data using a separate script, [rodent_db.R](https://github.com/ropensci/restez/blob/master/other/rodent_db.R).

In order for the docs to build on any given machine, that `rodent_db.R` script must be run first, which would then create a database (~10gb) in `restez/rodents`

I didn't envisage this to be a problem, as I never thought the docs would be built remotely.

**Comment by jeroen** [comment]
Maybe you can pre-knit the vignette, and put the `.md` file with the code output in the vignette folder? See for example: https://github.com/jeroen/jsonlite/blob/master/vignettes/precompile.R

**Comment by DomBennett** [comment]
Added: https://github.com/ropensci/restez/blob/master/vignettes/precompile.R

Does that work for you now?

**Comment by jeroen** [comment]
Not yet (you can see the last build logs on the left here): https://dev.ropensci.org/job/restez/

**Comment by DomBennett** [comment]
OK. Now it's fixed! https://dev.ropensci.org/job/restez/

**Comment by jeroen** [comment]
ok great -> https://docs.ropensci.org/restez/

**Comment by jeroen** [comment]
Thanks for making it work! Would you mind adding https://docs.ropensci.org/restez/ to the package description  URL field?

**Comment by DomBennett** [comment]
Sure. Like this: https://github.com/ropensci/restez/blob/master/DESCRIPTION

?

**Comment by jeroen** [comment]
Yes thanks. Issue resolved 👍

**Comment by DomBennett** [comment]
Thanks 👍
