### ISSUE TITLE
archived on CRAN

### ISSUE THREAD

**Issue by sckott** [ropensci/restez#18]
hi @DomBennett - just noticed that this pkg has been archived on CRAN since April last year https://cloud.r-project.org/web/packages/restez/ - Anything we can do to help get it back on CRAN?

**Comment by DomBennett** [comment]
hi @sckott 

I'm actually waiting for the R package of duckdb to appear on CRAN. Once that happens I'll update restez to remove the monetdblite dependency and switch to duck db. I think other ROpenSci packages have the same issue, right?

**Comment by sckott** [comment]
Ah, okay. Hadn't heard about the duckdb thing

**Comment by jeroen** [comment]
dockdb is on cran, do you still plan to maintain the package @DomBennett ?
