### ISSUE TITLE
db_download error!

### ISSUE THREAD

**Issue by bioxenia** [ropensci/restez#19]
Hello! I am trying to run the package restez, following the example of the supersmartR-workshopmaster. It keeps giving me the same error, that i'm not connected to the internet, although i am. This is the script that was used. Have you got any idea of what could be the problem? 
`
>library(restez)
>rstz_pth <- file.path(tempdir(), 'unannotated_database')
>if (!dir.exists(rstz_pth)) {
  dir.create(rstz_pth)
}
>restez_path_set(filepath = rstz_pth)
>db_download(preselection = '20')
`
And this is the error: 
Error: Unable to connect to 'https://www.ncbi.nlm.nih.gov/'Are you connected to the internet?

**Comment by DomBennett** [comment]
Are you able to navigate to https://www.ncbi.nlm.nih.gov/ ? All the internal is doing is making sure you can connect to that address.

**Comment by bioxenia** [comment]
Hello again, and thank you so much for your quick response! I have access to the internet and i am able to navigate to ncbi web page. Maybe the problem is in my software? I am using Windows 10. Do i need to have installed first some other programms or packages before running restez? Sorry for the silly questions but i am a begginer in R programming!

**Comment by jeroen** [comment]
There was a bug due to a broken dependency. I have now fixed it, can you try to restart R and then reinstall the package:

```r
remotes::install_github("ropensci/restez")
```
