### ISSUE TITLE
New Maintainer Wanted

### ISSUE THREAD

**Issue by maelle** [ropensci/restez#23]
If you're interested, please comment in the issue. 
For more info, see

* [our guidance on _Changing package maintainers_](https://devguide.ropensci.org/changing-maintainers.html);
* [our _Package Curation Policy_](https://devguide.ropensci.org/curationpolicy.html).

**Comment by joelnitta** [comment]
I am interested in becoming a maintainer for this package

**Comment by maelle** [comment]
Awesome news, thank you! I've invited you to the ropensci organization and the restez team that has admin access to this repo.

Note that to join the ropensci GitHub organization you'll need to enable 2FA if you haven't already done so: https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication

**Comment by maelle** [comment]
(I've removed your repo access as outside collaborator just to keep things streamlined)

**Comment by joelnitta** [comment]
@maelle Thanks! I accepted the invitation to join the ropensci org

**Comment by maelle** [comment]
Welcome :smile_cat:
