### ISSUE TITLE
db_download issue

### ISSUE THREAD

**Issue by Maxim-Karpov** [ropensci/restez#49]
Hello,

When attempting to use db_download I get the following error message:

Looking up latest GenBank release ...
... release number 256
... found 7304 sequence files
─────────────────────────────────────────────────────────────────────────
Which sequence file types would you like to download?
Choose from those listed below:
• 1  - 'Invertebrate'
        1564 files and 662 GB
Error in typesizes[[typ_nm]] : subscript out of bounds
In addition: Warning messages:
1: In identify_downloadable_files() :
  NAs introduced by coercion to integer range
2: In identify_downloadable_files() :
  Not all file information could be ascertained.
**ERROR:  Error in typesizes[[typ_nm]] : subscript out of bounds**
 
Trying again, attempt number 1

Perhaps the function no longer works with the current release?

**Comment by joelnitta** [comment]
@Maxim-Karpov thanks for the bug report! I'm traveling this week but will try to check when I get back.
